const chambas = {
  invierno: [
    "⛷️ • Enseñas a turistas a esquiar en una estación de lujo, obtienes:|min:8000|max:14500",
    "☕ • Preparas chocolate caliente en un café acogedor, obtienes:|min:6000|max:11000",
    "🎄 • Decoras árboles de Navidad en un centro comercial, obtienes:|min:7000|max:13500",
    "🧤 • Tejes bufandas personalizadas para una familia, obtienes:|min:6500|max:12000",
    "🧊 • Tallas esculturas de hielo en un festival invernal, obtienes:|min:9000|max:15000",
    "🦌 • Alimentas y cuidas renos en una reserva natural, obtienes:|min:8500|max:14800",
    "🏂 • Guías clases de snowboard en la montaña, obtienes:|min:9000|max:14900",
    "🎬 • Apoyas en sets de películas navideñas, por tu trabajo obtienes:|min:7000|max:14000",
    "⛸️ • Das mantenimiento a una pista de patinaje sobre hielo, obtienes:|min:6500|max:13000",
    "🔥 • Vendes leña para las chimeneas de las cabañas, obtienes:|min:5500|max:10500",
    "💡 • Instalas luces navideñas en las casas del vecindario, obtienes:|min:7500|max:14200",
    "🛷 • Guías paseos en trineo tirado por perros, obtienes:|min:9500|max:15000",
    "☃️ • Creas muñecos de nieve artísticos para un concurso, obtienes:|min:5000|max:9500",
    "🎁 • Trabajas como elfo envolviendo regalos en un taller, obtienes:|min:6000|max:11500",
    "🎶 • Cantas villancicos con un coro en la plaza pública, obtienes:|min:5500|max:10800",
    "🚚 • Conduces un camión quitanieve después de una tormenta, obtienes:|min:8500|max:14900",
    "🧥 • Modelas la nueva colección de abrigos de invierno, obtienes:|min:7000|max:13800",
    "🍲 • Cocinas sopa caliente en un puesto de mercado invernal, obtienes:|min:6800|max:12500",
    "📸 • Tomas fotografías de paisajes nevados para postales, obtienes:|min:8200|max:14600",
    "🚠 • Operas el teleférico de una montaña nevada, obtienes:|min:7800|max:14000",
    "🏒 • Arbitras un partido de hockey sobre hielo amateur, obtienes:|min:7200|max:13200",
    "🍞 • Horneas pan de jengibre para una pastelería local, obtienes:|min:6300|max:11800",
    "🚗 • Pones cadenas para nieve en los autos de los turistas, obtienes:|min:5800|max:11000",
    "📝 • Escribes cartas personalizadas de Santa Claus para niños, obtienes:|min:5200|max:10000",
    "🧸 • Reparas juguetes viejos para donarlos en Navidad, obtienes:|min:4800|max:9000",
    "🌰 • Vendes castañas asadas en un carrito ambulante, obtienes:|min:5600|max:10900",
    "🥶 • Pruebas la resistencia de ropa térmica en cámaras de frío, obtienes:|min:9800|max:15000",
    "📖 • Lees cuentos de invierno a niños en una librería, obtienes:|min:5900|max:11200",
    "❄️ • Eres un 'cazador de tormentas' y reportas el clima, obtienes:|min:8700|max:14700",
    "🏨 • Trabajas como recepcionista en un hotel de ski, obtienes:|min:7100|max:13100",
    "🚜 • Operas una máquina para crear nieve artificial en las pistas, obtienes:|min:8300|max:14400",
    "🍷 • Sirves vino caliente especiado en un mercado navideño, obtienes:|min:6600|max:12200",
    "✨ • Creas globos de nieve artesanales para vender, obtienes:|min:6100|max:11600",
    "🎭 • Actúas en una pastorela comunitaria, obtienes:|min:5300|max:10300",
    "🕯️ • Haces velas con aromas invernales (pino, canela), obtienes:|min:5700|max:10700",
    "🐕 • Paseas perros con abrigos especiales por la nieve, obtienes:|min:6400|max:11900",
    "🎣 • Guías una excursión de pesca en hielo, obtienes:|min:8900|max:14950",
    "🏠 • Construyes una casa de jengibre gigante para exhibición, obtienes:|min:9200|max:15000",
    "📦 • Ayudas en un centro de paquetería durante la alta demanda, obtienes:|min:7300|max:13400",
    "🔔 • Tocas campanas para una organización benéfica, obtienes:|min:4500|max:8500",
    "🧭 • Guías una caminata con raquetas de nieve por el bosque, obtienes:|min:7600|max:13900",
    "🔒 • Ayudas a gente a entrar a sus autos congelados, obtienes:|min:6700|max:12400",
    "👨‍🏫 • Impartes un taller sobre seguridad en avalanchas, obtienes:|min:9400|max:14800",
    "🦌 • Creas figuras de animales con ramas y piñas secas, obtienes:|min:5100|max:9800",
    "🎶 • Seleccionas la música para una pista de patinaje, obtienes:|min:6200|max:11300",
    "🍿 • Vendes palomitas de maíz en un autocinema de películas navideñas, obtienes:|min:5400|max:10600",
    "🧹 • Limpias chimeneas antes de que comience el frío, obtienes:|min:8100|max:14100",
    "👑 • Interpretas al Rey Mago en un desfile, obtienes:|min:7700|max:13700",
    "🍯 • Preparas remedios caseros para la tos y los vendes, obtienes:|min:5000|max:9600",
    "🆘 • Patrullas las pistas de esquí buscando a gente que necesita ayuda, obtienes:|min:9700|max:15000",
    "🎍 • Fabrican coronas de adviento para las iglesias, obtienes:|min:6900|max:12800",
    "🎿 • Das mantenimiento y enceras esquís y snowboards, obtienes:|min:7400|max:13600",
    "🏛️ • Guías un tour por un museo durante las vacaciones, obtienes:|min:7900|max:14000",
    "🗺️ • Diseñas mapas de rutas seguras para montañismo invernal, obtienes:|min:8400|max:14300",
    "🧩 • Creas rompecabezas con imágenes de paisajes nevados, obtienes:|min:4900|max:9200",
    "🍫 • Eres catador de nuevas líneas de chocolate caliente, obtienes:|min:8600|max:14700",
    "😇 • Montas nacimientos en casas y negocios, obtienes:|min:6000|max:11100",
    "🐴 • Guías paseos a caballo por senderos nevados, obtienes:|min:9100|max:14900",
    "📰 • Repartes periódicos en las mañanas más frías del año, obtienes:|min:5500|max:10400",
    "♨️ • Supervisas el funcionamiento de saunas y baños de vapor, obtienes:|min:7000|max:12900",
    "📸 • Alquilas cámaras instantáneas a turistas en la nieve, obtienes:|min:6300|max:11700",
    "🏗️ • Revisas estructuras por el peso de la nieve, obtienes:|min:9300|max:14900",

    "🎨 • Pintas copos de nieve en los escaparates de las tiendas, obtienes:|min:6800|max:12600",
    "🚑 • Eres conductor de ambulancia en una zona montañosa, obtienes:|min:9600|max:15000",
    "📆 • Vendes calendarios con tus fotos de invierno, obtienes:|min:5200|max:10100",
    "🌟 • Coordinas un evento de encendido del árbol de Navidad, obtienes:|min:8800|max:14800",
    "🎈 • Inflas globos de helio para la fiesta de Fin de Año, obtienes:|min:4700|max:8800",
    "🍜 • Preparas ramen caliente en un food truck, obtienes:|min:7200|max:13300",

    "🐦 • Construyes y vendes comederos para pájaros, obtienes:|min:5100|max:9700",
    "📝 • Haces el inventario de una tienda de regalos, obtienes:|min:6400|max:11400",
    "🔥 • Mantienes encendidas las fogatas en un resort de montaña, obtienes:|min:5900|max:10900",
    "📚 • Forras los libros de texto para el nuevo semestre, obtienes:|min:5300|max:10200",
    "🛏️ • Cambias la ropa de cama en un hostal de montaña, obtienes:|min:6700|max:12300",
    "💪 • Ayudas a empujar autos atascados en la nieve, obtienes:|min:4600|max:8600",
    "🤸 • Das clases de yoga en un estudio con calefacción, obtienes:|min:7500|max:13800",
    "🧗 • Supervisas una pared de escalada interior, obtienes:|min:8000|max:14000",
    "🎮 • Pruebas un nuevo videojuego con temática invernal, obtienes:|min:9000|max:14900",
    "🤔 • Organizas un torneo de ajedrez en una cabaña, obtienes:|min:6500|max:12000",
    "🚗 • Eres valet parking en un restaurante de lujo en la montaña, obtienes:|min:7100|max:13000",
    "🐶 • Cuidas las mascotas de la gente que se va de vacaciones, obtienes:|min:7800|max:13900",
    "🎉 • Limpias después de las fiestas de Navidad y Año Nuevo, obtienes:|min:8500|max:14500",
    "💡 • Cambias los focos del alumbrado público en la nieve, obtienes:|min:7600|max:13600",
    "🧊 • Repartes sal en las banquetas para que no se congelen, obtienes:|min:5800|max:10700",
    "☕ • Tuestas granos de café para una edición especial de invierno, obtienes:|min:8200|max:14200",
    "🧣 • Vendes ropa térmica en un puesto de la montaña, obtienes:|min:7300|max:13500",
    "📦 • Empacas kits de supervivencia para el frío, obtienes:|min:6900|max:12700",
    "📖 • Editas una antología de cuentos de Navidad, obtienes:|min:8400|max:14400",
    "🗺️ • Actualizas los mapas de las pistas de ski, obtienes:|min:9100|max:14800",
    "🎸 • Tocas música tranquila junto a la chimenea de un hotel, obtienes:|min:7700|max:13700",
  ],
  verano: [
    "🏖️ • Vigilas bañistas como salvavidas en la playa, obtienes:|min:9000|max:15000",
    "🍧 • Vendes nieves artesanales en el malecón, obtienes:|min:7000|max:12000",
    "🌴 • Organizas fiestas temáticas en hoteles de la Riviera, obtienes:|min:10000|max:15000",
    "🚤 • Guías tours en lancha por manglares y lagunas, obtienes:|min:8000|max:14500",
    "🎸 • Animas noches bohemias en bares al aire libre, obtienes:|min:6500|max:11500",
    "🥥 • Recolectas cocos para bebidas tropicales, obtienes:|min:7500|max:13000",
    "🏄 • Enseñas surf a principiantes en la playa, obtienes:|min:9000|max:14800",
    "🎡 • Operas juegos mecánicos en la feria de verano, obtienes:|min:7000|max:13500",
    "🍹 • Preparas cocteles exóticos en un bar de playa, obtienes:|min:8500|max:14000",
    "🏐 • Arbitras un torneo de voleibol playero, obtienes:|min:6000|max:11000",
    "🏰 • Construyes castillos de arena gigantes para un hotel, obtienes:|min:5000|max:10000",
    "🍦 • Inventas un nuevo sabor de helado para una heladería, obtienes:|min:7500|max:14200",
    "🏊 • Limpias y das mantenimiento a piscinas de lujo, obtienes:|min:8000|max:14600",
    "🐠 • Guías una expedición de esnórquel en un arrecife, obtienes:|min:9500|max:15000",
    "🍉 • Vendes rebanadas de sandía fresca en un puesto, obtienes:|min:5500|max:10500",
    "⛺ • Ayudas a montar un campamento de verano para niños, obtienes:|min:7000|max:12500",
    "🔥 • Organizas fogatas con malvaviscos en la playa, obtienes:|min:6200|max:11200",
    "📸 • Eres fotógrafo en bodas que se celebran junto al mar, obtienes:|min:11000|max:15000",
    "🛶 • Rentas kayaks y paddlesurf en un lago, obtienes:|min:7800|max:13800",
    "👨‍🍳 • Eres el parrillero estrella en un restaurante al aire libre, obtienes:|min:8800|max:14900",
    "☀️ • Instalas paneles solares en los techos de las casas, obtienes:|min:9200|max:14950",
    "🌬️ • Das mantenimiento a sistemas de aire acondicionado, obtienes:|min:8700|max:14700",
    "🦟 • Fumigas casas y jardines contra los mosquitos, obtienes:|min:7300|max:13300",
    "💧 • Vendes botellas de agua fría a los corredores en el parque, obtienes:|min:4500|max:8500",
    "😎 • Vendes lentes de sol y sombreros en un quiosco, obtienes:|min:5800|max:10800",
    "🚗 • Lavas coches a mano bajo el sol, obtienes:|min:6100|max:11100",
    "🍓 • Recolectas moras y frambuesas en una granja, obtienes:|min:6900|max:12900",
    "🎬 • Proyectas películas al aire libre en un parque, obtienes:|min:7600|max:13600",
    "🎵 • Eres DJ en una fiesta de piscina, obtienes:|min:9300|max:15000",
    "🧗 • Guías tours de escalada en roca al amanecer, obtienes:|min:8900|max:14800",
    "🌳 • Podas árboles y cortas el césped de jardines, obtienes:|min:7200|max:13200",
    "🎈 • Vendes globos con formas de animales en la feria, obtienes:|min:5100|max:9800",
    "📖 • Coordinas un club de lectura de verano en la biblioteca, obtienes:|min:5700|max:10700",
    "🎨 • Haces tatuajes temporales de henna en la playa, obtienes:|min:6400|max:11900",
    "🚲 • Reparas y rentas bicicletas cerca de la ciclopista, obtienes:|min:7100|max:13100",
    "🗺️ • Eres guía turístico en tu propia ciudad, obtienes:|min:8400|max:14400",
    "🍿 • Operas el puesto de palomitas y refrescos en el cine, obtienes:|min:6000|max:11000",
    "🤿 • Enseñas a bucear a principiantes en una piscina, obtienes:|min:9100|max:14900",
    "🌮 • Preparas tacos de mariscos en un food truck, obtienes:|min:8200|max:14100",
    "🐬 • Eres entrenador de delfines en un acuario, obtienes:|min:9800|max:15000",
    "🌺 • Diseñas collares de flores para fiestas hawaianas, obtienes:|min:5600|max:10600",
    "🧳 • Trabajas como botones en un hotel de playa, obtienes:|min:6700|max:12700",
    "🧘 • Das clases de yoga al amanecer en la playa, obtienes:|min:7700|max:13700",
    "✈️ • Ayudas a coordinar vuelos de parapente, obtienes:|min:10500|max:15000",
    "🐚 • Recolectas conchas marinas para hacer artesanías, obtienes:|min:4900|max:9200",
    "🏄‍♂️ • Reparas tablas de surf y bodyboard, obtienes:|min:8300|max:14300",
    "🏖️ • Instalas y retiras sombrillas y camastros en la playa, obtienes:|min:5900|max:10900",
    "🎣 • Llevas a turistas a pescar en mar abierto, obtienes:|min:9600|max:14950",
    "🧊 • Vendes bolsas de hielo a los restaurantes y bares, obtienes:|min:5300|max:10200",
    "🥑 • Cosechas aguacates para guacamole, obtienes:|min:7400|max:13400",
    "🪂 • Doblas paracaídas para una escuela de paracaidismo, obtienes:|min:9400|max:14850",
    "🛝 • Eres el probador de toboganes en un parque acuático, obtienes:|min:9700|max:15000",
    "🌊 • Mides la calidad del agua en diferentes playas, obtienes:|min:8600|max:14600",
    "💡 • Organizas lunadas con música y cuentos, obtienes:|min:6600|max:12600",
    "🐢 • Vigilas nidos de tortugas marinas para protegerlos, obtienes:|min:8100|max:14000",
    "🏗️ • Ayudas a montar los escenarios de los festivales de música, obtienes:|min:7900|max:13900",
    "🍌 • Haces postres helados de plátano en la playa, obtienes:|min:5400|max:10400",
    "🎽 • Vendes camisetas con diseños veraniegos, obtienes:|min:6300|max:11300",
    "🛥️ • Limpias yates y veleros en la marina, obtienes:|min:9900|max:14900",
    "🥭 • Haces mangos preparados con chile y limón, obtienes:|min:5200|max:10100",
    "🏖️ • Escribes mensajes en la arena para propuestas y anuncios, obtienes:|min:4800|max:9000",
    "🛣️ • Pintas las líneas de las carreteras que se borraron con el sol, obtienes:|min:8000|max:14000",
    "🎪 • Eres un artista callejero en el malecón, obtienes:|min:6800|max:12800",
    "🪁 • Enseñas a niños a volar cometas en la playa, obtienes:|min:5000|max:9500",
    "🗺️ • Creas mapas del tesoro para juegos infantiles, obtienes:|min:4700|max:8800",
    "🛶 • Guías un tour nocturno en kayak para ver el plancton, obtienes:|min:9200|max:14800",
    "🏨 • Limpias las habitaciones de un hotel con vista al mar, obtienes:|min:7000|max:13000",
    "🦐 • Ayudas en un barco camaronero al amanecer, obtienes:|min:8500|max:14500",
    "🧗‍♀️ • Equipas rutas de escalada en acantilados marinos, obtienes:|min:9500|max:14950",
    "🧱 • Construyes hornos de leña para pizzas al aire libre, obtienes:|min:8700|max:14700",
    "🍻 • Sirves cerveza artesanal en un festival de verano, obtienes:|min:7200|max:13200",
    "🤸‍♀️ • Das clases de acrobacias en la playa, obtienes:|min:7800|max:13800",
    "🍋 • Haces y vendes litros de limonada fresca, obtienes:|min:4600|max:8600",
    "🚶‍♂️ • Guías caminatas a cascadas escondidas, obtienes:|min:8400|max:14400",
    "🕊️ • Organizas liberaciones de mariposas en eventos, obtienes:|min:6900|max:12900",
    "🦀 • Buscas cangrejos en las rocas con los niños, obtienes:|min:5500|max:10500",
    "🌶️ • Preparas y vendes ceviche fresco, obtienes:|min:8600|max:14600",
    "🏄‍♀️ • Participas como extra en un comercial de surf, obtienes:|min:7600|max:13600",
    "🪵 • Construyes cabañas de madera para campamentos, obtienes:|min:9300|max:14900",
    "🔥 • Eres experto en shows con fuego en la playa, obtienes:|min:10000|max:15000",
    "🚗 • Diriges el tráfico en el estacionamiento de la playa, obtienes:|min:5800|max:10800",
    "📝 • Haces encuestas a turistas sobre su experiencia, obtienes:|min:6500|max:11500",
    "🧼 • Lavas la loza en un restaurante de playa muy concurrido, obtienes:|min:6200|max:11200",
    "📦 • Abasteces los minibares de las habitaciones de hotel, obtienes:|min:6700|max:12700",
    "🏛️ • Limpias estatuas y monumentos en el calor, obtienes:|min:7400|max:13400",
    "💧 • Instalas sistemas de riego en jardines, obtienes:|min:8100|max:14100",
    "🏖️ • Alisas la arena de la playa con un tractor por la noche, obtienes:|min:8300|max:14300",
  ],
  primavera: [
    "🌸 • Armas arreglos florales para bodas al aire libre, obtienes:|min:8500|max:14800",
    "🐝 • Manejas colmenas en una granja ecológica, obtienes:|min:7000|max:13000",
    "🚴 • Guías paseos ciclistas por campos en flor, obtienes:|min:6000|max:11000",
    "🎨 • Pintas murales en festivales de arte urbano, obtienes:|min:9000|max:15000",
    "🍓 • Cosechas fresas en una huerta orgánica, obtienes:|min:7500|max:14000",
    "🦋 • Llevas recorridos para ver mariposas en reservas, obtienes:|min:7000|max:12500",
    "🌱 • Plantas y cuidas plántulas en un vivero, obtienes:|min:6500|max:11500",
    "🧺 • Organizas picnics gourmet en parques nacionales, obtienes:|min:8000|max:14200",
    "🐦 • Guías tours de avistamiento de aves migratorias, obtienes:|min:7200|max:13500",
    "🏡 • Trabajas como jardinero paisajista en residencias, obtienes:|min:8800|max:14900",
    "🥚 • Decoras huevos de Pascua para un evento comunitario, obtienes:|min:5500|max:10000",
    "🏞️ • Haces limpieza de primavera en un parque natural, obtienes:|min:6000|max:11200",
    "📸 • Tomas fotos de familias en campos llenos de flores, obtienes:|min:9500|max:15000",
    "🪁 • Vendes cometas artesanales en un día de campo, obtienes:|min:5800|max:10800",
    "🍷 • Participas en la primera cata de vinos de la temporada, obtienes:|min:7800|max:14000",
    "🏞️ • Haces mantenimiento de senderos para caminatas, obtienes:|min:6900|max:12900",
    "🧼 • Lavas ventanas de edificios altos para recibir la primavera, obtienes:|min:8100|max:14500",
    "👨‍🌾 • Vendes productos frescos en un mercado de agricultores, obtienes:|min:6700|max:12700",
    "🎈 • Organizas un festival de globos aerostáticos, obtienes:|min:10500|max:15000",
    "✏️ • Escribes poemas sobre la naturaleza para una revista local, obtienes:|min:5000|max:9500",
    "🐑 • Ayudas en el esquilado de ovejas en una granja, obtienes:|min:7300|max:13300",
    "🌳 • Plantas árboles como parte de una campaña de reforestación, obtienes:|min:6200|max:11800",

    "💧 • Limpias fuentes y monumentos de la ciudad, obtienes:|min:7600|max:13600",
    "🐇 • Te disfrazas del Conejo de Pascua en un centro comercial, obtienes:|min:6400|max:12400",
    "🥕 • Siembras hortalizas en un huerto comunitario, obtienes:|min:5900|max:10900",
    "🚜 • Preparas la tierra para la siembra con un tractor, obtienes:|min:8600|max:14600",
    "🐮 • Ayudas a cuidar terneros recién nacidos en un establo, obtienes:|min:7100|max:13100",
    "🛶 • Limpias los ríos de basura acumulada en invierno, obtienes:|min:6800|max:12800",
    "🎨 • Pintas bancas y juegos en los parques públicos, obtienes:|min:6600|max:12600",
    "📚 • Organizas una venta de libros usados al aire libre, obtienes:|min:5700|max:10700",
    "🕊️ • Construyes y colocas casas para pájaros en el bosque, obtienes:|min:5400|max:10400",
    "🤸 • Das clases de ejercicio al aire libre en un parque, obtienes:|min:7400|max:13400",
    "💍 • Ayudas a planear propuestas de matrimonio en jardines botánicos, obtienes:|min:9200|max:14950",
    "🍓 • Haces mermelada casera con las primeras frutas, obtienes:|min:6100|max:11100",
    "🍃 • Recolectas hierbas medicinales que crecen en primavera, obtienes:|min:5600|max:10600",
    "🍄 • Guías un taller para identificar hongos de primavera, obtienes:|min:8400|max:14400",

    "🧀 • Aprendes a hacer queso fresco con leche de cabra, obtienes:|min:7700|max:13700",
    "🏛️ • Quitas el polvo en un museo de historia natural, obtienes:|min:6300|max:12300",
    "🎣 • Repueblas un lago con peces jóvenes, obtienes:|min:8200|max:14100",
    "⛺ • Impermeabilizas tiendas de campaña antes de la temporada, obtienes:|min:5300|max:10200",
    "🥳 • Organizas fiestas de cumpleaños infantiles en jardines, obtienes:|min:8300|max:14300",
    "🚲 • Eres guía en una ruta de ciclismo de montaña, obtienes:|min:9100|max:14900",
    "🌬️ • Mides la calidad del aire después del invierno, obtienes:|min:8700|max:14700",
    "📸 • Tomas fotografías con drones de los campos en flor, obtienes:|min:9800|max:15000",
    "🛍️ • Ayudas a cambiar los escaparates de las tiendas a la moda primaveral, obtienes:|min:6500|max:12500",
    "🍵 • Creas una mezcla de té con flores de la estación, obtienes:|min:7000|max:13000",
    "🏢 • Lavas a presión el exterior de los edificios, obtienes:|min:8900|max:14800",
    "🚗 • Detallas autos para quitarles la suciedad del invierno, obtienes:|min:7900|max:13900",
    "🌾 • Plantas arroz en campos inundados, obtienes:|min:7500|max:13500",
    "💖 • Haces ramos de flores para el Día de las Madres, obtienes:|min:9300|max:14900",
    "🏞️ • Revisas y reparas puentes de madera en senderos, obtienes:|min:9000|max:14850",
    "🐌 • Recolectas caracoles para restaurantes gourmet, obtienes:|min:5200|max:10100",
    "🐸 • Guías un tour nocturno para escuchar el canto de las ranas, obtienes:|min:6000|max:11000",
    "🎻 • Tocas el violín en un jardín botánico, obtienes:|min:8000|max:14000",
    "🗑️ • Coordinas un día de limpieza comunitaria, obtienes:|min:5000|max:9800",
    "🍋 • Cosechas limones y naranjas, obtienes:|min:6900|max:12900",
    "🗺️ • Creas mapas de las mejores rutas para ver flores silvestres, obtienes:|min:7200|max:13200",
    "🐕 • Bañas perros que jugaron en el lodo primaveral, obtienes:|min:6800|max:12800",
    "🪁 • Ayudas en un concurso de vuelo de cometas, obtienes:|min:5800|max:10800",
    "👒 • Diseñas y vendes sombreros para el sol, obtienes:|min:7100|max:13100",
    "🏃 • Marcas la ruta para una carrera de 5k, obtienes:|min:6200|max:11200",
    "🌮 • Vendes tacos de canasta en un partido de béisbol, obtienes:|min:5500|max:10500",
    "🏫 • Pintas el exterior de una escuela durante las vacaciones, obtienes:|min:8500|max:14500",
    "📦 • Haces la mudanza de estudiantes que cambian de dormitorio, obtienes:|min:7300|max:13300",
    "🌱 • Injertas árboles frutales para crear nuevas variedades, obtienes:|min:9400|max:14900",
    "🧘‍♀️ • Lideras una sesión de meditación en la naturaleza, obtienes:|min:7000|max:13000",
    "🗿 • Creas esculturas para jardín con materiales reciclados, obtienes:|min:8800|max:14800",
    "🍯 • Recolectas la primera miel de la temporada, obtienes:|min:9600|max:15000",
    "🧪 • Tomas muestras de suelo para analizar sus nutrientes, obtienes:|min:7600|max:13600",
    "📷 • Haces un documental sobre el despertar de la naturaleza, obtienes:|min:10000|max:15000",
    "🥐 • Horneas pan con flores comestibles, obtienes:|min:6700|max:12700",

    "🚚 • Repartes tierra y abono a los jardineros, obtienes:|min:7000|max:13000",
    "🛍️ • Vendes artesanías en un mercado de primavera, obtienes:|min:6100|max:11100",
    "🔍 • Buscas tréboles de cuatro hojas para la buena suerte, obtienes:|min:4500|max:8500",
    "💧 • Instalas colectores de agua de lluvia, obtienes:|min:8000|max:14000",
    "🎨 • Impartes un taller de pintura de paisajes al aire libre, obtienes:|min:8400|max:14400",
    "🚶 • Reparas banquetas dañadas por el hielo del invierno, obtienes:|min:7800|max:13800",
    "🍓 • Preparas aguas frescas con frutas de temporada, obtienes:|min:5900|max:10900",
    "🏞️ • Eres guardabosques en un parque nacional, obtienes:|min:9200|max:14950",
    "📚 • Organizas la biblioteca de una escuela, obtienes:|min:6600|max:12600",
    "🎉 • Decoras para fiestas de graduación, obtienes:|min:8200|max:14200",
    "🐶 • Entrenas cachorros en un parque, obtienes:|min:7700|max:13700",
    "💡 • Revisas y reparas las luces de los jardines públicos, obtienes:|min:7400|max:13400",
    "🚗 • Llevas a cabo la verificación vehicular, obtienes:|min:6900|max:12900",
    "🍷 • Sirves vino en un viñedo durante los tours, obtienes:|min:7500|max:13500",
    "😁 • Eres anfitrión en un restaurante con terraza, obtienes:|min:6300|max:12300",
  ],
  otoño: [
    "🍂 • Limpias caminos barriendo hojas en parques históricos, obtienes:|min:6000|max:11000",
    "🎃 • Diseñas calabazas para concursos de Halloween, obtienes:|min:8000|max:14000",
    "🌰 • Recolectas nueces silvestres en el bosque, obtienes:|min:6500|max:12500",
    "🦉 • Llevas recorridos nocturnos en bosques misteriosos, obtienes:|min:9000|max:15000",
    "🍁 • Organizas ferias gastronómicas de temporada, obtienes:|min:10000|max:15000",
    "📚 • Narras cuentos en bibliotecas durante tardes lluviosas, obtienes:|min:7000|max:13000",
    "🧙 • Preparas escenarios para festivales de magia y misterio, obtienes:|min:8000|max:14500",
    "🌽 • Guías a personas a través de un laberinto de maíz gigante, obtienes:|min:7500|max:13500",
    "🍎 • Ayudas en la cosecha de manzanas en una huerta, obtienes:|min:6800|max:12800",
    "👻 • Eres guía en un tour de leyendas y fantasmas por la ciudad, obtienes:|min:8500|max:14800",
    "🥧 • Horneas pays de calabaza para una pastelería local, obtienes:|min:7200|max:13200",
    "💀 • Decoras altares para el Día de Muertos, obtienes:|min:9500|max:15000",
    "☕ • Eres barista experto en lattes con especias de otoño, obtienes:|min:6900|max:12900",
    "📸 • Fotografías los colores del otoño para un calendario, obtienes:|min:8800|max:14900",
    "👹 • Creas disfraces de Halloween personalizados, obtienes:|min:9200|max:14950",
    "🍇 • Participas en la vendimia, recolectando uvas para vino, obtienes:|min:7600|max:13600",
    "🍄 • Eres guía experto en recolección de hongos comestibles, obtienes:|min:8300|max:14300",
    "🕯️ • Fabrican velas aromáticas con olores de la estación, obtienes:|min:6400|max:11400",
    "🧟 • Maquillas actores para una atracción de casa embrujada, obtienes:|min:9000|max:14900",
    "🧥 • Ayudas en una tienda a cambiar al inventario de otoño, obtienes:|min:6100|max:11100",
    "👻 • Trabajas como actor de sustos en una casa del terror, obtienes:|min:8200|max:14200",
    "🚗 • Preparas los coches para el invierno (anticongelante, llantas), obtienes:|min:7800|max:13800",
    "🎨 • Pintas calaveritas de azúcar, obtienes:|min:6600|max:12600",
    "🍞 • Haces pan de muerto para vender, obtienes:|min:7100|max:13100",
    "📦 • Empacas kits de decoración para Halloween, obtienes:|min:5800|max:10800",
    "🔥 • Vendes leña para las primeras noches frías, obtienes:|min:5900|max:10900",
    "🏈 • Vendes comida en un partido de fútbol americano colegial, obtienes:|min:6300|max:11300",
    "🏠 • Ayudas a la gente a decorar sus casas para Halloween, obtienes:|min:7700|max:13700",
    "📽️ • Organizas un maratón de películas de terror, obtienes:|min:7000|max:13000",
    "🍩 • Haces donas de sidra de manzana, obtienes:|min:6700|max:12700",
    "🎶 • Creas una playlist de música espeluznante para fiestas, obtienes:|min:5200|max:10200",
    "🧩 • Diseñas acertijos para un 'escape room' temático, obtienes:|min:8600|max:14600",
    "🐴 • Guías paseos en carreta con heno por el campo, obtienes:|min:7400|max:13400",
    "🍷 • Eres sommelier en una cata de vinos de cosecha tardía, obtienes:|min:9100|max:14900",
    "💧 • Limpias canaletas llenas de hojas secas, obtienes:|min:8100|max:14100",
    "🧑‍🏫 • Das clases de regularización a estudiantes, obtienes:|min:7300|max:13300",
    "🐿️ • Recolectas bellotas para proyectos de reforestación, obtienes:|min:5000|max:9500",
    "📖 • Forras libros y cuadernos para el regreso a clases, obtienes:|min:5400|max:10400",
    "💀 • Escribes 'calaveritas literarias' por encargo, obtienes:|min:5600|max:10600",
    "🪓 • Cortas y apilas leña para el invierno, obtienes:|min:6200|max:11200",
    "🧣 • Tejes suéteres y los vendes en un mercado artesanal, obtienes:|min:7000|max:13000",
    "🍯 • Preparas conservas y mermeladas con frutas de la cosecha, obtienes:|min:6800|max:12800",
    "🥔 • Cosechas papas, zanahorias y otras hortalizas de raíz, obtienes:|min:6500|max:12500",
    "🧟‍♂️ • Diriges un 'flashmob' de zombies en un centro comercial, obtienes:|min:8700|max:14700",
    "🖼️ • Enmarcas cuadros con hojas de otoño prensadas, obtienes:|min:5700|max:10700",
    "🦉 • Construyes refugios para aves nocturnas, obtienes:|min:5900|max:10900",
    "🖋️ • Practicas caligrafía para invitaciones de fiestas, obtienes:|min:6900|max:12900",
    "🔍 • Organizas una búsqueda del tesoro con temática de otoño, obtienes:|min:7200|max:13200",
    "🍵 • Tuestas semillas de calabaza con diferentes especias, obtienes:|min:5500|max:10500",
    "⚰️ • Construyes ataúdes de utilería para decoraciones, obtienes:|min:8400|max:14400",
    "🕸️ • Colocas telarañas falsas en casas y negocios, obtienes:|min:6000|max:11000",
    "🐶 • Diseñas disfraces de Halloween para mascotas, obtienes:|min:7500|max:13500",
    "🎻 • Tocas música melancólica en un café, obtienes:|min:7100|max:13100",
    "🤔 • Eres el anfitrión de una noche de trivia en un pub, obtienes:|min:7600|max:13600",
    "🔥 • Supervisas una quema controlada de rastrojo, obtienes:|min:9300|max:14950",

    "🚲 • Guardas y das mantenimiento a las bicicletas de verano, obtienes:|min:6600|max:12600",
    "🛋️ • Cubres y proteges los muebles de jardín para el invierno, obtienes:|min:6400|max:12400",
    "📚 • Haces el inventario en una librería antes de la temporada alta, obtienes:|min:7000|max:13000",
    "🦇 • Guías un tour para observar murciélagos al atardecer, obtienes:|min:8000|max:14000",
    "🌶️ • Cosechas chiles y los pones a secar, obtienes:|min:6800|max:12800",
    "📸 • Haces sesiones de fotos con humo de colores en el bosque, obtienes:|min:9400|max:14900",
    "📜 • Investigas historias de terror locales para contarlas, obtienes:|min:8800|max:14800",
    "🍿 • Haces palomitas de maíz acarameladas para vender, obtienes:|min:5300|max:10300",
    "🐺 • Imitas aullidos de lobo en un tour nocturno, obtienes:|min:5000|max:9800",
    "⛪ • Limpias y decoras iglesias para el Día de Todos los Santos, obtienes:|min:6700|max:12700",
    "🧙‍♀️ • Lees las cartas del tarot en una feria de Halloween, obtienes:|min:7800|max:13800",
    "🍁 • Creas un catálogo de los tipos de hojas de los árboles, obtienes:|min:5100|max:10100",
    "🍻 • Eres juez en un festival de cerveza tipo 'Oktoberfest', obtienes:|min:9600|max:15000",
    "💨 • Aísles ventanas y puertas en las casas contra el frío, obtienes:|min:8500|max:14500",
    "🌽 • Desgranas maíz para hacer harina, obtienes:|min:6100|max:11100",
    "🎭 • Diriges una obra de teatro de misterio, obtienes:|min:9800|max:15000",
    "🎃 • Vendes todo tipo de calabazas en la carretera, obtienes:|min:7300|max:13300",
    "🕯️ • Guías un recorrido por un cementerio histórico, obtienes:|min:8900|max:14850",
    "🎶 • Afinas pianos en escuelas y salas de conciertos, obtienes:|min:9000|max:14900",
    "⚗️ • Creas pociones 'mágicas' (bebidas sin alcohol) para fiestas, obtienes:|min:7400|max:13400",
    "📦 • Empacas y envías los suéteres feos de Navidad, obtienes:|min:6900|max:12900",
    "🤖 • Programas los sustos automáticos de una casa del terror, obtienes:|min:9700|max:15000",
    "📖 • Lees historias de Edgar Allan Poe en voz alta, obtienes:|min:7000|max:13000",
    "🍜 • Preparas sopa de calabaza en un restaurante, obtienes:|min:7200|max:13200",
    "🎥 • Filmas un cortometraje de terror en el bosque, obtienes:|min:9500|max:14950",
    "💐 • Haces arreglos florales con cempasúchil, obtienes:|min:8200|max:14200",
    "🎨 • Body painting de monstruos y criaturas, obtienes:|min:9200|max:14900",
    "🤫 • Eres el guardián silencioso que asusta al final del recorrido, obtienes:|min:7700|max:13700",
    "🍎 • Operas una prensa de manzanas para hacer sidra, obtienes:|min:8300|max:14300",
    "🚶‍♂️ • Barres las banquetas de tu vecindario llenas de hojas, obtienes:|min:4800|max:9000",
  ],
  eventos: [
    "🎆 • Eres el diseñador principal del show de fuegos artificiales de Año Nuevo, obtienes:|min:28000|max:35000",
    "🎭 • Coreografías una comparsa para el Carnaval de Río, obtienes:|min:25000|max:34000",
    "🎤 • Eres el ingeniero de sonido del escenario principal en Coachella, obtienes:|min:26000|max:33000",
    "🎉 • Organizas el Grito de Independencia en el Zócalo, obtienes:|min:22000|max:30000",
    "👻 • Diseñas y construyes una casa del terror para un parque temático, obtienes:|min:24000|max:32000",
    "💘 • Coordinas una propuesta de matrimonio masiva en Times Square, obtienes:|min:20000|max:28000",
    "🎬 • Eres juez en el Festival de Cine de Cannes, obtienes:|min:29000|max:35000",
    "🎪 • Eres el director de pista del Cirque du Soleil, obtienes:|min:27000|max:34500",
    "🏁 • Agitas la bandera a cuadros en la final de la F1 en Mónaco, obtienes:|min:30000|max:35000",
    "🍔 • Eres el juez principal en el World Championship of BBQ, obtienes:|min:21000|max:29000",
    "🎈 • Diseñas el globo principal para el desfile de Macy's, obtienes:|min:26000|max:33500",
    "🤖 • Presentas un nuevo robot humanoide en el CES de Las Vegas, obtienes:|min:28000|max:34800",
    "📖 • Eres el moderador de una plática con un autor ganador del Nobel, obtienes:|min:23000|max:31000",
    "🎧 • Eres el DJ principal en el festival Tomorrowland, obtienes:|min:29000|max:35000",
    "🎨 • Pintas las caras de los actores de una superproducción de Hollywood, obtienes:|min:20000|max:27000",
    "🛡️ • Organizas la justa principal en una feria medieval internacional, obtienes:|min:22000|max:29500",
    "💐 • Eres el florista principal de una boda real, obtienes:|min:30000|max:35000",
    "🤵 • Coordinas la seguridad de la gala de los Premios Oscar, obtienes:|min:25000|max:32500",
    "📦 • Eres el director de logística del Maratón de Nueva York, obtienes:|min:27000|max:34000",
    "✍️ • Eres el anfitrión de un taller de escritura con un autor famoso, obtienes:|min:19000|max:26000",
    "🏆 • Pules el trofeo de la Copa del Mundo antes de la final, obtienes:|min:24000|max:31500",
    "🚀 • Coordinas el lanzamiento de un producto para una mega empresa de tecnología, obtienes:|min:28000|max:34900",
    "👗 • Diriges el backstage de un desfile en la Semana de la Moda de París, obtienes:|min:26000|max:33800",
    "⚽ • Eres el árbitro principal de la final de la Champions League, obtienes:|min:30000|max:35000",
    "🏛️ • Curas una nueva exhibición para el Museo del Louvre, obtienes:|min:27000|max:34200",
    "🎤 • Eres el 'calentador' de público para la grabación de un especial de comedia, obtienes:|min:19000|max:25000",
    "🎮 • Eres el comentarista principal de la final mundial de League of Legends, obtienes:|min:25000|max:32000",
    "🏎️ • Lideras el equipo de pits de un piloto de Nascar, obtienes:|min:29000|max:34700",
    "🚁 • Piloteas el helicóptero que filma el Tour de Francia, obtienes:|min:28000|max:34500",
    "🧪 • Creas los efectos especiales de humo y fuego para un concierto de rock, obtienes:|min:23000|max:30500",
    "💡 • Diseñas la iluminación del escenario para un show de Broadway, obtienes:|min:24000|max:31800",
    "📜 • Eres el subastador de un objeto histórico en Sotheby's, obtienes:|min:27000|max:33900",
    "🌍 • Organizas una conferencia de paz en las Naciones Unidas, obtienes:|min:30000|max:35000",
    "🍣 • Eres el chef principal en la cena de gala de los embajadores, obtienes:|min:26000|max:33000",
    "🦁 • Coreografías una escena de batalla para una película épica, obtienes:|min:22000|max:29800",
    "📸 • Eres el fotógrafo oficial de la familia real en un evento, obtienes:|min:28000|max:34600",
    "🐘 • Coordinas el transporte de animales exóticos para un zoológico, obtienes:|min:21000|max:28500",
    "💎 • Valúas las joyas que se usarán en la Met Gala, obtienes:|min:29000|max:34900",
    "📈 • Presentas el keynote de apertura en una convención de negocios, obtienes:|min:25000|max:32200",
    "🌊 • Coordinas un simulacro de rescate a gran escala, obtienes:|min:20000|max:27500",
    "🎶 • Conduces la Orquesta Filarmónica en el Concierto de Año Nuevo de Viena, obtienes:|min:30000|max:35000",
    "📚 • Eres el traductor simultáneo para un líder mundial, obtienes:|min:27000|max:34000",
    "🍷 • Eres el catador que otorga la medalla de oro en un concurso mundial de vinos, obtienes:|min:24000|max:31000",
    "🕊️ • Organizas la liberación de palomas en la apertura de los Juegos Olímpicos, obtienes:|min:19000|max:26500",
    "🧊 • Esculpes un bar completo de hielo para una fiesta exclusiva, obtienes:|min:23000|max:30000",
    "💥 • Eres el doble de acción para el actor principal en una escena peligrosa, obtienes:|min:28000|max:34800",
    "🗺️ • Planeas la ruta para un rally de coches clásicos por todo el país, obtienes:|min:22000|max:29000",
    "🛰️ • Supervisas la transmisión satelital de un evento global, obtienes:|min:29000|max:34900",
    "🤯 • Creas un truco de magia a gran escala para un especial de TV, obtienes:|min:26000|max:33300",
    "🎂 • Diseñas y horneas el pastel para el centenario de una ciudad, obtienes:|min:21000|max:28800",
    "🤫 • Negocias los contratos de los artistas para un festival masivo, obtienes:|min:28000|max:34700",
    "🤵 • Eres el mayordomo personal de un dignatario durante una cumbre, obtienes:|min:25000|max:32800",
    "🏙️ • Proyectas un video mapping sobre un edificio icónico, obtienes:|min:27000|max:34100",
    "🤯 • Eres el hipnotista del show principal en un crucero de lujo, obtienes:|min:19000|max:26800",
    "🐴 • Eres el comentarista de la carrera del Derby de Kentucky, obtienes:|min:24000|max:31200",
    "📜 • Autenticas un manuscrito recién descubierto de un autor famoso, obtienes:|min:29000|max:35000",
    "🌴 • Paisajista de una isla privada para la fiesta de un millonario, obtienes:|min:28000|max:34400",
    "🚁 • Coordinas una flota de helicópteros para un tour aéreo VIP, obtienes:|min:26000|max:33600",
    "✨ • Eres el 'hada madrina' que consigue lo imposible en la Fundación Make-A-Wish, obtienes:|min:30000|max:35000",
    "🎤 • Escribes el discurso de aceptación de un premio para una celebridad, obtienes:|min:20000|max:27800",
    "🔍 • Lideras la investigación de un caso para un programa de 'true crime', obtienes:|min:22000|max:29200",
    "🐉 • Eres el titiritero principal de un dragón gigante en un desfile de Año Nuevo Chino, obtienes:|min:23000|max:30800",
    "⚖️ • Arbitras una negociación de alto nivel entre dos corporaciones, obtienes:|min:29000|max:34900",
    "🤿 • Lideras una expedición para filmar un documental en la Fosa de las Marianas, obtienes:|min:30000|max:35000",
    "🏺 • Supervisas el traslado de artefactos para la exhibición de Tutankamón, obtienes:|min:28000|max:34500",
    "🌟 • Pules las estrellas del Paseo de la Fama de Hollywood, obtienes:|min:19000|max:25500",
    "🎩 • Custodias los secretos de un mago famoso, obtienes:|min:21000|max:28200",
    "🗣️ • Eres la voz del estadio en la inauguración de un mundial, obtienes:|min:25000|max:32500",
    "🧭 • Trazas el recorrido de la antorcha olímpica, obtienes:|min:27000|max:33700",
    "🛰️ • Calibras el telescopio espacial Hubble para un descubrimiento, obtienes:|min:30000|max:35000",
    "🧬 • Presentas un avance revolucionario en una convención médica mundial, obtienes:|min:29000|max:34800",
    "🗿 • Lideras la restauración de una de las cabezas de la Isla de Pascua, obtienes:|min:28000|max:34200",
    "🎶 • Seleccionas la música para la coronación de un nuevo monarca, obtienes:|min:26000|max:33000",
    "🚤 • Capitaneas el yate del ganador del Gran Premio de Mónaco, obtienes:|min:24000|max:31500",
    "📝 • Eres el 'ghost writer' de la autobiografía de una leyenda del rock, obtienes:|min:23000|max:30500",
    "🧗 • Eres el guía principal en una expedición al Monte Everest, obtienes:|min:30000|max:35000",
    "💡 • Inventas y patentas el juguete más popular de la temporada navideña, obtienes:|min:28000|max:34000",
    "👨‍⚖️ • Das el veredicto en un concurso de talentos internacional, obtienes:|min:25000|max:32000",
    "📸 • Tomas la foto de portada para la revista TIME, obtienes:|min:29000|max:34900",
    "🌍 • Creas un doodle de Google para un evento mundial, obtienes:|min:22000|max:29500",
    "🛸 • Lideras un panel sobre avistamientos OVNI en una convención, obtienes:|min:19000|max:26000",
    "🦖 • Ensamblas el esqueleto de un T-Rex para una exhibición de museo, obtienes:|min:27000|max:33800",
    "🧑‍🚀 • Entrenas a los actores de una película espacial en gravedad cero, obtienes:|min:28000|max:34600",
    "💧 • Bendices el barco antes de su viaje inaugural, obtienes:|min:20000|max:27000",
    "🃏 • Eres el 'crupier' en la mesa final de la Serie Mundial de Póker, obtienes:|min:26000|max:33500",
    "🕰️ • Das cuerda al Big Ben en la víspera de Año Nuevo, obtienes:|min:30000|max:35000",
    "🔥 • Eres un bombero paracaidista en un incendio forestal masivo, obtienes:|min:29000|max:34800",
    "🗺️ • Descubres y nombras una nueva isla en una expedición, obtienes:|min:28000|max:34500",
    "🎻 • Tocas un Stradivarius en un concierto privado para la realeza, obtienes:|min:27000|max:34000",
  ],
};

function pickRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function getTemporada(fecha = new Date()) {
  const mes = fecha.getMonth() + 1;
  if ([12, 1, 2].includes(mes)) return "invierno";
  if ([3, 4, 5].includes(mes)) return "primavera";
  if ([6, 7, 8].includes(mes)) return "verano";
  if ([9, 10, 11].includes(mes)) return "otoño";
  return "verano";
}

function chamba(tema) {
  let lista = chambas[tema];
  if (!lista || lista.length === 0)
    return { autor: "🜲 ᵖᵃᵗᵒ", status: false, data: null };
  let raw = pickRandom(lista);
  let [work, min, max] = raw.split("|").map((s) => s.trim());
  return {
    autor: "🜲 ᵖᵃᵗᵒ",
    status: true,
    data: {
      work,
      min_pay: parseInt(min.replace("min:", "")),
      max_pay: parseInt(max.replace("max:", "")),
    },
  };
}

export { chamba, getTemporada };
